version: "3.9"

services:
  nginx:
    container_name: nginxsql
    build: ./nginx/
    ports:
      - 8887:80
      # - 8333:443 #if need ssl
    volumes:
      - ./code/public:/srv/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm

  phpfpm:
    container_name: phpfpmsql
    build: ./php/
    volumes:
      - ./code:/srv/www
      - ./php/configs:/usr/local/etc/php/conf.d

  mysql:
    container_name: mysqlsql
    image: mysql:latest
    ports:
      - 3337:3306
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
